"""add year

Revision ID: 7960cbd08a58
Revises: 6b4827e19e24
Create Date: 2025-07-05 11:12:59.456308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7960cbd08a58'
down_revision: Union[str, Sequence[str], None] = '6b4827e19e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'year')
    # ### end Alembic commands ###
