"""Initial user migration file

Revision ID: d88f2f7252a9
Revises: 
Create Date: 2025-08-16 13:43:35.879530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd88f2f7252a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    # op.drop_table('todos')
    # op.drop_table('SequelizeMeta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('SequelizeMeta',
    # sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('name', name=op.f('SequelizeMeta_pkey'))
    # )
    # op.create_table('todos',
    # sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    # sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name=op.f('todos_pkey'))
    # )
    op.drop_table('users')
    # ### end Alembic commands ###
